# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3gg8fBYIxo6vxG92pKCP-VHLXV-8uMN
"""

!pip install diffusers transformers accelerate

import torch
from diffusers import DiffusionPipeline,DPMSolverMultistepScheduler
from diffusers.utils import export_to_video

pipe=DiffusionPipeline.from_pretrained("damo-vilab/text-to-video-ms-1.7b",torch_dtype=torch.float16,variant="fp16")
pipe.scheduler=DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload

pipe = pipe.to("cuda")

prompt="spider man surfing"
video_frames =pipe(prompt,num_inference_steps=25).frames
frames=video_frames[0]
video_path=export_to_video(frames)
video_name=video_path.replace('/tmp','')
print('Name:',video_name)
torch.cuda.empty_cache()

